name: ruff-code-scanning

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read
  security-events: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - id: fmt
        name: Check formatting (ruff format --check)
        run: ruff format --check .
        continue-on-error: true

      - id: lint
        name: Run Ruff (SARIF)
        if: ${{ always() }}         # ← fmt が失敗しても実行
        run: ruff check . --output-format sarif --output-file ruff.sarif
        continue-on-error: true

      - name: Upload SARIF to GitHub
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ruff.sarif
          category: ruff

      # ここで最終判定: どちらかが失敗なら Job を失敗にする
      - name: Fail job if any check failed
        if: ${{ steps.fmt.outcome == 'failure' || steps.lint.outcome == 'failure' }}
        run: |
          echo "Formatting or lint failed. See annotations and SARIF." >&2
          exit 1

